<?php
 $_catalog_array=array(
	'0' => array(
		'1' => array(
			'id' => '1',
			'classname' => '关于我们',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '2,3,4',
			'sort_order' => '1',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'aboutus',
		),
		'5' => array(
			'id' => '5',
			'classname' => '商业机会',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '6',
			'sort_order' => '5',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'opportunity',
		),
		'7' => array(
			'id' => '7',
			'classname' => '政策法规',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '8',
			'sort_order' => '7',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'regulations',
		),
		'9' => array(
			'id' => '9',
			'classname' => '解决方案',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '10',
			'sort_order' => '9',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'solution',
		),
		'15' => array(
			'id' => '15',
			'classname' => '物联网产品',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '16',
			'sort_order' => '15',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'product',
		),
		'17' => array(
			'id' => '17',
			'classname' => '应用案例',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '18',
			'sort_order' => '17',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'case',
		),
		'19' => array(
			'id' => '19',
			'classname' => '联系我们',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '20',
			'sort_order' => '19',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'contactus',
		),
		'21' => array(
			'id' => '21',
			'classname' => '专家建议',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '22',
			'sort_order' => '21',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
		'23' => array(
			'id' => '23',
			'classname' => '物联网应用',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '24',
			'sort_order' => '23',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
		'25' => array(
			'id' => '25',
			'classname' => '企业专栏 ',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '26',
			'sort_order' => '25',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
		'27' => array(
			'id' => '27',
			'classname' => '行业标准',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '28',
			'sort_order' => '27',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
		'29' => array(
			'id' => '29',
			'classname' => '聚焦农业',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '30',
			'sort_order' => '29',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
		'31' => array(
			'id' => '31',
			'classname' => '农产品信息',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '32',
			'sort_order' => '31',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
		'33' => array(
			'id' => '33',
			'classname' => '名企介绍',
			'parentid' => '0',
			'classpath' => '',
			'childcount' => '0',
			'classdepth' => '1',
			'childidarr' => '',
			'sort_order' => '33',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'1' => array(
		'2' => array(
			'id' => '2',
			'classname' => '网站简介',
			'parentid' => '1',
			'classpath' => '1',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '2',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'aboutus',
		),
		'3' => array(
			'id' => '3',
			'classname' => '网站荣誉',
			'parentid' => '1',
			'classpath' => '1',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '3',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'aboutus',
		),
		'4' => array(
			'id' => '4',
			'classname' => '网站文化',
			'parentid' => '1',
			'classpath' => '1',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '4',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'aboutus',
		),
	),
	'5' => array(
		'6' => array(
			'id' => '6',
			'classname' => '商业机会',
			'parentid' => '5',
			'classpath' => '5',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '6',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'opportunity',
		),
	),
	'7' => array(
		'8' => array(
			'id' => '8',
			'classname' => '政策法规',
			'parentid' => '7',
			'classpath' => '7',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '8',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'regulations',
		),
	),
	'9' => array(
		'10' => array(
			'id' => '10',
			'classname' => '解决方案',
			'parentid' => '9',
			'classpath' => '9',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '10',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'solution',
		),
	),
	'15' => array(
		'16' => array(
			'id' => '16',
			'classname' => '物联网产品',
			'parentid' => '15',
			'classpath' => '15',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '16',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'product',
		),
	),
	'17' => array(
		'18' => array(
			'id' => '18',
			'classname' => '应用案例',
			'parentid' => '17',
			'classpath' => '17',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '18',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'case',
		),
	),
	'19' => array(
		'20' => array(
			'id' => '20',
			'classname' => '联系我们',
			'parentid' => '19',
			'classpath' => '19',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '20',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => 'contactus',
		),
	),
	'21' => array(
		'22' => array(
			'id' => '22',
			'classname' => '专家建议',
			'parentid' => '21',
			'classpath' => '21',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '22',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'23' => array(
		'24' => array(
			'id' => '24',
			'classname' => '物联网应用',
			'parentid' => '23',
			'classpath' => '23',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '24',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'25' => array(
		'26' => array(
			'id' => '26',
			'classname' => '企业专栏 ',
			'parentid' => '25',
			'classpath' => '25',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '26',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'27' => array(
		'28' => array(
			'id' => '28',
			'classname' => '行业标准',
			'parentid' => '27',
			'classpath' => '27',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '28',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'29' => array(
		'30' => array(
			'id' => '30',
			'classname' => '聚焦农业',
			'parentid' => '29',
			'classpath' => '29',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '30',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'31' => array(
		'32' => array(
			'id' => '32',
			'classname' => '农产品信息',
			'parentid' => '31',
			'classpath' => '31',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '32',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
	'33' => array(
		'34' => array(
			'id' => '34',
			'classname' => '名企介绍',
			'parentid' => '33',
			'classpath' => '33',
			'childcount' => '0',
			'classdepth' => '2',
			'childidarr' => '',
			'sort_order' => '34',
			'classimg' => '',
			'classintro' => '',
			'classtype' => '0',
			'classpage' => '',
		),
	),
)?>